### ISSUE TITLE
sans/sans-serif mean the same?

### ISSUE THREAD

**Issue by den1k** [kushidesign/kushi#39]
https://github.com/kushidesign/kushi/blob/095f9852d426d0b58ec0cdc06fb278dbdf05353b/src/kushi/ui/utility.cljc#L212-L213

`sans` just means without and `sans` on it's own is often used as a short form for `sans-serif` so maybe the two options should be `sans` and `serif`?

**Comment by den1k** [comment]
currently use of `.sans-serif` results in a serif font:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/4651810/216380200-279e20fe-25ac-44ba-ad82-feeace1705ab.png">

**Comment by paintparty** [comment]
Typo! Thanks den!
Closed via #40
